/**
 * Name -> real asset under public/assets. Sources and licences:
 * docs/ASSETS.md (photos: Wikimedia Commons; shapes/icons: Twemoji).
 */
export const ASSETS = {
  "icon-matching": "/assets/icon-matching.svg",
  "icon-color": "/assets/icon-color.svg",
  "icon-size": "/assets/icon-size.svg",
  "icon-drawing": "/assets/icon-drawing.svg",
  "icon-memory": "/assets/icon-memory.svg",
  "icon-fruit": "/assets/icon-fruit.svg",
  "icon-vehicle": "/assets/icon-vehicle.svg",
  circle: "/assets/circle.svg",
  square: "/assets/square.svg",
  triangle: "/assets/triangle.svg",
  diamond: "/assets/diamond.svg",
  star: "/assets/star.svg",
  heart: "/assets/heart.svg",
  ring: "/assets/ring.svg",
  plus: "/assets/plus.svg",
  cat: "/assets/cat.jpg",
  dog: "/assets/dog.jpg",
  fish: "/assets/fish.jpg",
  bird: "/assets/bird.jpg",
  frog: "/assets/frog.jpg",
  rabbit: "/assets/rabbit.jpg",
  cow: "/assets/cow.jpg",
  chicken: "/assets/chicken.jpg",
  duck: "/assets/duck.jpg",
  pig: "/assets/pig.jpg",
  dolphin: "/assets/dolphin.jpg",
  shark: "/assets/shark.jpg",
  mango: "/assets/mango.jpg",
  banana: "/assets/banana.jpg",
  orange: "/assets/orange.jpg",
  guava: "/assets/guava.jpg",
  watermelon: "/assets/watermelon.jpg",
  papaya: "/assets/papaya.jpg",
  longan: "/assets/longan.jpg",
  mangosteen: "/assets/mangosteen.jpg",
  durian: "/assets/durian.jpg",
  lychee: "/assets/lychee.jpg",
  dragonfruit: "/assets/dragonfruit.jpg",
  avocado: "/assets/avocado.jpg",
  tomato: "/assets/tomato.jpg",
  carrot: "/assets/carrot.jpg",
  potato: "/assets/potato.jpg",
  corn: "/assets/corn.jpg",
  pumpkin: "/assets/pumpkin.jpg",
  pineapple: "/assets/pineapple.jpg",
  motorbike: "/assets/motorbike.jpg",
  bicycle: "/assets/bicycle.jpg",
  car: "/assets/car.jpg",
  bus: "/assets/bus.jpg",
  truck: "/assets/truck.jpg",
  firetruck: "/assets/firetruck.jpg",
  ambulance: "/assets/ambulance.jpg",
  train: "/assets/train.jpg",
  airplane: "/assets/airplane.jpg",
  helicopter: "/assets/helicopter.jpg",
  ship: "/assets/ship.jpg",
  boat: "/assets/boat.jpg",
  canoe: "/assets/canoe.jpg",
  sampan: "/assets/sampan.jpg",
  ferry: "/assets/ferry.jpg",
  cyclo: "/assets/cyclo.jpg",
  cablecar: "/assets/cablecar.jpg",
  coach: "/assets/coach.jpg",
} as const;

export type AssetName = keyof typeof ASSETS;

export const SHAPE_NAMES = [
  "circle",
  "square",
  "triangle",
  "diamond",
  "star",
  "heart",
  "ring",
  "plus",
] as const satisfies readonly AssetName[];

export const ANIMAL_NAMES = [
  "cat",
  "dog",
  "fish",
  "bird",
  "frog",
  "rabbit",
  "cow",
  "chicken",
  "duck",
  "pig",
  "dolphin",
  "shark",
] as const satisfies readonly AssetName[];

export const FRUIT_VEG_NAMES = [
  "mango",
  "banana",
  "orange",
  "guava",
  "watermelon",
  "papaya",
  "longan",
  "mangosteen",
  "durian",
  "lychee",
  "dragonfruit",
  "avocado",
  "tomato",
  "carrot",
  "potato",
  "corn",
  "pumpkin",
  "pineapple",
] as const satisfies readonly AssetName[];

export const VEHICLE_NAMES = [
  "motorbike",
  "bicycle",
  "car",
  "bus",
  "truck",
  "firetruck",
  "ambulance",
  "train",
  "airplane",
  "helicopter",
  "ship",
  "boat",
  "canoe",
  "sampan",
  "ferry",
  "cyclo",
  "cablecar",
  "coach",
] as const satisfies readonly AssetName[];
